name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://cloud189-shandong-person.oos-sdqd.ctyunapi.cn/1c911b79-bf14-40c5-b222-0e5199d65d3f?x-amz-CLIENTTYPEIN=UNKNOWN&AWSAccessKeyId=caf5e6901807aca55a45&x-amz-UID=441135222&x-amz-APPID=828221&response-content-disposition=attachment%3Bfilename%3D%22Simplicity-Auto%40MIX%202_DEV-20200417-20.3.26-9.0-2166406f.zip%22%3Bfilename*%3DUTF-8%27%27Simplicity-Auto%2540MIX%2B2_DEV-20200417-20.3.26-9.0-2166406f.zip&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=PERSON&x-amz-limit=rate%3D10240%2Cconcurrency%3D12&Signature=54tTlcOnmPzYjit9VR5OhWXDR%2B8%3D&x-amz-SHID=1146611094401&Expires=1639646409&x-amz-FSIZE=1907427530&x-amz-UFID=61473112469629371KeyId=caf5e6901807aca55a45&x-amz-UID=441135222&x-amz-APPID=828221&response-content-disposition=attachment%3Bfilename%3D%22Simplicity-Auto%40MIX%202_DEV-20200417-20.3.26-9.0-2166406f.zip%22%3Bfilename*%3DUTF-8%27%27Simplicity-Auto%2540MIX%2B2_DEV-20200417-20.3.26-9.0-2166406f.zip&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=PERSON&x-amz-limit=rate%3D10240%2Cconcurrency%3D12&Signature=x7Iw82HTZHt%2BoHghfhtQhuHN/oA%3D&x-amz-SHID=1146611094401&Expires=1639644480&x-amz-FSIZE=1907427530&x-amz-UFID=61473112469629371
  ROM_NAME: MIUI
  BUILD_TYPE: Aonly
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
